repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(.venv/|__pycache__/)

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(.venv/|__pycache__/)

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,W503,E501"]
        exclude: ^(.venv/|__pycache__/)

  # Disable mypy for initial release - too many type annotation requirements
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-PyYAML, types-requests]
  #       exclude: ^(.venv/|__pycache__/)
  #       args: ["--ignore-missing-imports"]
