[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
extend-exclude = '''
/(
    \.venv
  | __pycache__
  | \.git
  | build
  | dist
  | \.mypy_cache
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip_glob = [".venv/*", "__pycache__/*", "build/*", "dist/*"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
