name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install formatting tools
      run: pip install black isort
    - name: Check formatting with black
      run: black --check --diff .
    - name: Check import sorting with isort
      run: isort --check-only --diff .

  lint:
    runs-on: ubuntu-latest
    needs: format-check
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install linting tools
      run: pip install flake8
    - name: Lint with flake8
      run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: [format-check, lint]
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test syntax compilation
      run: |
        python -m py_compile run_task.py
        python -c "import src.llm, src.context, src.git_ops, src.test_runner, src.complexity_analyzer, src.budget_monitor, src.context_cache, src.premium_features"

    - name: Test configuration loading
      run: |
        python -c "
        import yaml
        with open('config.yaml', 'r') as f:
            config = yaml.safe_load(f)
        print('✅ Config validation passed')
        "

    - name: Run basic functionality tests
      run: |
        # Test help output
        python run_task.py --help
        
        # Test budget report (should work without API key)
        python run_task.py --budget-report || echo "Budget report test completed"
        
        # Test cache stats
        python run_task.py --cache-stats || echo "Cache stats test completed"
      env:
        ANTHROPIC_API_KEY: "dummy-key-for-testing"
        REPO_PATH: "/tmp/test-repo"

  security-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install security tools
      run: |
        pip install bandit safety
    - name: Run Bandit security scan
      run: |
        bandit -c .bandit.yml -r . -f json -o bandit-report.json || true
        bandit -c .bandit.yml -r .

    - name: Check dependencies for security vulnerabilities
      run: |
        safety check --json --output safety-report.json || true
        safety check
      continue-on-error: true  # Don't fail on safety warnings initially

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install markdownlint
      run: npm install -g markdownlint-cli2
    - name: Lint Markdown files
      run: markdownlint-cli2 "**/*.md" --config .markdownlint.json
